### ISSUE TITLE
Image set on a task definition should be respected

### ISSUE THREAD

**Issue by tkram01** [PrefectHQ/prefect-aws#138]
When using an ECSTask if you specify a task definition ARN prefect will replace its image with the base prefect image unless you pass the image parameter to the ECSTask.

**Comment by madkinsz** [comment]
@tkram01 if you set the image to `None` e.g. `ECSTask(image=None, ...)` we will not overwrite your task definition's image. I agree it'd be nice if we handled this better. Unfortunately, unlike https://github.com/PrefectHQ/prefect/pull/7244, we cannot see the task definition at declaration time and would not know if an `image` is present until runtime. This means that we cannot infer `None` for the image field for you. It's important that Prefect's default for the image field is applied at declaration time and not runtime because we need it to match the Python/Prefect version's you create the deployment with.

**Comment by madkinsz** [comment]
@ahuang11 / @anna-geller  perhaps we should default the image to `None` if a task definition arn is set. I see this as a point of confusion often and I'm not sure it's even possible to create a task definition without an image?

**Comment by madkinsz** [comment]
@tkram01 would that be a better experience for you?

**Comment by tkram01** [comment]
@madkinsz Yes. That would be less confusing.

**Comment by anna-geller** [comment]
> I'm not sure it's even possible to create a task definition without an image

@madkinsz you are 100% correct on that, you always need the image, here is an example https://github.com/anna-geller/dataflow-ops/blob/main/task-definition.json#L5 

this makes so much sense - if task_arn is provided, we should set image to None 👍

**Comment by madkinsz** [comment]
@ahuang11 would you be comfortable taking this one?

We'll want to watch out for the case where the image is null and they have not defined a "prefect" container in their task definition.

**Comment by ahuang11** [comment]
I will take a look!
