### ISSUE TITLE
Attributes docstring missing from AwsCredentials and ECSTask

### ISSUE THREAD

**Issue by discdiver** [PrefectHQ/prefect-aws#185]
Maybe also missing from others. Discussed with Andrew.

Screenshots attached. 

Ideally there would be type hints and a clear example of saving a block in the docstring.
<img width="995" alt="Screenshot 2023-01-03 at 12 51 15 PM" src="https://user-images.githubusercontent.com/7703961/210414506-d51a114d-888c-4a26-80b7-e9324849d624.png">
<img width="788" alt="Screenshot 2023-01-03 at 12 51 27 PM" src="https://user-images.githubusercontent.com/7703961/210414507-16622801-2ef6-4890-bb20-49dc9f3b6c22.png">

**Comment by madkinsz** [comment]
Previously the Pydantic `Field` descriptions were parsed. I'm not sure why they're not anymore. That's how the ECS options are documented. I have a preference for keeping them there instead of in docstrings since they're sent to the API and parsing docstrings into descriptions is weird — but it sounds like this will require some investigation.
