### ISSUE TITLE
Prefect-aws==0.1.2 has a botocore==1.24.21 on Pipenv

### ISSUE THREAD

**Issue by aldwyn** [PrefectHQ/prefect-aws#94]
Hey Prefect team!

I've stumbled upon this Pipenv issue. When trying to execute the following:
`pipenv install prefect-aws`

It installs v0.1.2, but when pipenv is generating the lockfile, it has a `botocore==1.24.21` subdependency. I see that in this repo, it should be  `botocore==1.27.53`. There's a mismatch between this repo and the Pypi one perhaps? Because the v0.1.2 version in Pypi was updated last Aug 3, but the requirements.txt in this repo was updated last Aug 18.

Thanks in advance.

**Comment by desertaxle** [comment]
Hey @aldwyn! Yes, the reason you're seeing that discrepancy is because we haven't made a release since changing the  `botocore` dependency version. Note that we're updating the pin for `botocore` to accept a larger range in https://github.com/PrefectHQ/prefect-aws/pull/99 which will be reflected in the next release.

**Comment by ahuang11** [comment]
I think this should be fixed now; please re-open if not!
